---
 - hosts: dev
   become: yes
   tasks:
   - name: Add tomcat group
     group:
       name: tomcat

   - name: Add "tomcat" user
     user:
       name: tomcat
       group: tomcat
       home: /usr/share/tomcat
       createhome: no
       system: yes

   - name: Download Tomcat
     get_url:
       url: https://archive.apache.org/dist/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz
       dest: /home/ubuntu/tomcat

   - name: Create a tomcat directory
     file:
       path: /usr/share/tomcat
       state: directory
       owner: tomcat
       group: tomcat

   - name: Extract tomcat archive
     unarchive:
       src: "{{ tomcat_archive_dest }}"
       dest: /usr/share/tomcat
       owner: tomcat
       group: tomcat
       remote_src: yes
       extra_opts: "--strip-components=1"
       creates: /usr/share/tomcat/bin

   - name: Copy tomcat service file
     template:
       src: templates/tomcat.service.j2
       dest: /etc/systemd/system/tomcat.service
     when: ansible_service_mgr == "systemd"

   - name: Start and enable tomcat
     service:
       daemon_reload: yes
       name: tomcat
       state: started
       enabled: yes
     when: ansible_service_mgr == "systemd"

